In [2]:
print("hello coder")

hello coder


In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a= [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [6]:
c = ["hello",1,56,22.7,"good coder"]
print(c)

['hello', 1, 56, 22.7, 'good coder']


# vector and Matrix

In [7]:
# one dimensonal is vector and two dimensonal is matrix
l = [[1,2,3,4,5],[6,7,8,9,10]]
l

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [8]:
# in array
np.array(l)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# arange function

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# matriz zero
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# liner spacing

In [19]:
# liner spacing
arr1 = np.linspace(1,5,2)
arr1

array([1., 5.])

In [20]:
arr3 = np.linspace(1,5,5)
arr3

array([1., 2., 3., 4., 5.])

In [22]:
arr8 = np.linspace(1,10,15)
arr8

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

# Random Generation Function

In [23]:
# gives 0 to 1 some value called normalization
np.random.rand(5)

array([0.75067768, 0.24994304, 0.31409722, 0.57924268, 0.23180301])

In [24]:
# standazition -3 to +3 some value
np.random.randn(10)

array([-1.24604393,  2.78253411,  0.77074609,  1.3383205 , -0.20251281,
        0.75187226, -0.66710011,  0.53258638,  2.09733089,  1.17143633])

In [28]:
0-6 under some one value gives
np.random.randint(6)

3

In [29]:
np.random.randint(10,20,10)

array([14, 11, 15, 18, 19, 11, 14, 16, 11, 13], dtype=int32)

# Array Attributes

In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a.shape

(3, 3)

In [36]:
arr.size

6

In [37]:
arr.dtype

dtype('float64')

# Array Method

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a.min()

np.int64(1)

In [44]:
a.max()

np.int64(9)

In [45]:
a.sum()

np.int64(45)

In [51]:
# row and coloum case to some
# coloum wise 0- coloum
np.sum(a,axis=0)

array([12, 15, 18])

In [52]:
# row wise
np.sum(a,axis=1)

array([ 6, 15, 24])

In [53]:
a.mean()

np.float64(5.0)

In [54]:
a.std()

np.float64(2.581988897471611)

In [55]:
# index number max value
a.argmax()

np.int64(8)

In [56]:
# index number min value
a.argmin()

np.int64(0)

# Reshaping and Resizing

In [58]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [61]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [63]:
# resizing menas arr you save in that array
# it save as arr1
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
arr1 = arr1.reshape(4,5)

In [65]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Array Indexing and Slicing

In [66]:
import numpy as np

In [68]:
ar=np.arange(11,21)
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
# indexing
ar[3]

np.int64(14)

In [74]:
ar[0]

np.int64(11)

In [75]:
ar[6]

np.int64(17)

In [78]:
# slicing
ar[1:5]

array([12, 13, 14, 15])

In [79]:
ar[0:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
# with step
ar[:6:2]

array([11, 13, 15])

# Numpy Indxing and Slicing of Matrix

In [81]:
arr= np.arange(1,31).reshape(6,5)

In [82]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [83]:
arr[0]

array([1, 2, 3, 4, 5])

In [84]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[5]

array([26, 27, 28, 29, 30])

In [86]:
arr[0]

array([1, 2, 3, 4, 5])

In [87]:
arr[0,0]

np.int64(1)

In [88]:
arr[0,4]

np.int64(5)

In [90]:
arr[5,4]

np.int64(30)

In [92]:
arr[3,3]

np.int64(19)

In [94]:
# slicing
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [96]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [97]:
# coloum select- you select row all and which colum you give
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [98]:
# rowselect- you select coloum all and whichrow you give
arr[3,:]

array([16, 17, 18, 19, 20])

# boolen indexing

In [107]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [108]:
# in case give event nummber ?
bool_idx = arr%2==0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [109]:
arr= arr[bool_idx]
arr

array([12, 14, 16, 18, 20])

# Array Operation

In [110]:
import numpy as np

In [111]:
# Arithmatic operation
a1= np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [112]:
a1

array([1, 2, 3, 4, 5])

In [113]:
a2

array([ 6,  7,  8,  9, 10])

In [114]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [115]:
a1-a2

array([-5, -5, -5, -5, -5])

In [116]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [117]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [118]:
a1//a2

array([0, 0, 0, 0, 0])

In [119]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [120]:
# Broadcasting
l = [10,20,30,40]
arr = np.array(l)
arr+10

array([20, 30, 40, 50])

In [121]:
arr-2

array([ 8, 18, 28, 38])

In [137]:
# Deep and Shallow Copy
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [138]:
slice= a[:5]

In [139]:
slice

array([1, 2, 3, 4, 5])

In [140]:
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [141]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [142]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [143]:
# it changes copy person it change- deep copy 
b=a
b[0]=99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [152]:
# shallo copy- not chand a only b cane 
a
b=a.copy()
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [153]:
b[4]=10
b

array([99,  2,  3,  4, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [154]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix Opertion

In [2]:
import numpy as np

In [14]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8,9],[10,11,12],[13,14,15]])

In [15]:
mat1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
mat2

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
# matrix multipication
result= np.dot(mat1,mat2)
result

array([[ 66,  72,  78],
       [156, 171, 186]])

In [19]:
# matrix mltipication another method
mat1 @ mat2

array([[ 66,  72,  78],
       [156, 171, 186]])

In [20]:
# transpose of mat1
mat1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Advance Array Manipulation

In [23]:
# stacking array- only vector is stack not matrix
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [28]:
# spliting array
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
# array splic in equal split
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]